### ISSUE TITLE
What delegate should I write?

### ISSUE THREAD

**Issue by saminlu** [asifmujteba/iOSSharedViewTransition#5]
What delegate should I write?
I just use code instead of storyboard, I wrote the implement function but it didn't work, what other delegate should I  write?

**Comment by asifmujteba** [comment]
Please see the usage sample in description, u just need to set source, destination view controllers and navigation controller. After that continue performing segue either through code or storyboard is does not matter..

**Comment by saminlu** [comment]
Ok, I got it.  Thank you!
